# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---

include:
#  - board: xiao_ble
#    shield: roBa_dongle_display dongle_display
#    snippet: studio-rpc-usb-uart
#    artifact-name: zmk_dongle_display

#  - board: xiao_ble
#    shield: roBa_dongle_xiao
#    snippet: studio-rpc-usb-uart
#    artifact-name: zmk_dongle_xiao

#  - board: raytac_mdbt50q_rx
#    shield: roBa_dongle_raytac
#  #  snippet: studio-rpc-usb-uart
#    artifact-name: zmk_dongle_raytac

#  - board: xiao_ble
#    shield: roBa_R_peripheral rgbled_adapter
#    artifact-name: 1_roBa_R_peripheral

  - board: xiao_ble
    shield: roBa_R_central
    snippet: studio-rpc-usb-uart
    artifact-name: 2_roBa_R_central

#  - board: xiao_ble
#    shield: roBa_L_central rgbled_adapter
#    snippet: studio-rpc-usb-uart
#    artifact-name: 1_roBa_L_central
    
  - board: xiao_ble
    shield: roBa_L_peripheral 
    artifact-name: 2_roBa_L_peripheral

 # reset   
  - board: xiao_ble
    shield: settings_reset
#  - board: raytac_mdbt50q_rx
#    shield: settings_reset