# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---

include:
  - board: seeeduino_xiao_ble
    shield: zmk_dongle dongle_display
    snippet: common-config studio-rpc-usb-uart
    artifact-name: zmk_dongle
  - board: seeeduino_xiao_ble
    shield: roBa_R rgbled_adapter
    snippet: common-config studio-rpc-usb-uart
    artifact-name: roBa_central_R
  - board: seeeduino_xiao_ble
    shield: roBa_R rgbled_adapter
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: roBa_peripheral_R
  - board: seeeduino_xiao_ble
    shield: roBa_L rgbled_adapter
    snippet: common-config
    artifact-name: roba_peripheral_right

  - board: seeeduino_xiao_ble
    shield: rommana_dongle dongle_display
    snippet: common-config zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: roBa_dongle_with_logging
  - board: seeeduino_xiao_ble
    shield: roBa_R rgbled_adapter
    snippet: common-config zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: roBa_central_R_with_logging


 # reset   
  - board: seeeduino_xiao_ble
    shield: settings_reset