parse_config:
  raw_binding_map:
    '&mt_exit_AML_on_tap LEFT_SHIFT Z': 
      tap: "Z"
      hold: "$$mdi:apple-keyboard-shift$$"
      type: text_with_symbol

    '&sys_reset': "Reset"
    '&bootloader': "Boot"
    '&swapper': "Win Next"
    '&caps_word': "Caps Word"
    '&inv_qm': "¿"
    '&ind_bat': "Show Batt"
    '&ind_con': "Show Conn"
    '&mse_tog': {t: "MSE", h: "toggle"}
    '&ktap LC(LS(V))': "Plain P"

    '&out OUT_BLE': "$$mdi:bluetooth$$"
    '&out OUT_USB': "$$mdi:usb$$"
    '&out OUT_TOG':
      tap: "$$mdi:toggle-switch$$"
      hold: "$$mdi:bluetooth$$"
      shifted: "$$mdi:usb$$"
      type: toggle

    '&td_bt_clear':
      tap: "$$mdi:bluetooth$$"
      shifted: "$$mdi:close-thick$$"
      type: text_with_symbol
    '&td_bt_clear_all':
      tap: "$$mdi:bluetooth$$"
      shifted: "CLEAR ALL"
      type: text_with_symbol
   
    '&bt BT_CLR':
      tap: "$$mdi:bluetooth$$"
      shifted: "$$mdi:close-thick$$"
      type: text_with_symbol
    '&bt BT_SEL 0':
      tap: "$$mdi:bluetooth-connect$$"
      shifted: "0"
      type: text_with_symbol
    '&bt BT_SEL 1':
      tap: "$$mdi:bluetooth-connect$$"
      shifted: "1"
      type: text_with_symbol
    '&bt BT_SEL 2':
      tap: "$$mdi:bluetooth-connect$$"
      shifted: "2"
      type: text_with_symbol
    '&bt BT_SEL 3':
      tap: "$$mdi:bluetooth-connect$$"
      shifted: "3"
      type: text_with_symbol
    '&bt BT_SEL 4':
      tap: "$$mdi:bluetooth-connect$$"
      shifted: "4"
      type: text_with_symbol

    '&mmv MOVE_UP': "Mouse ↑"
    '&mmv MOVE_DOWN': "Mouse ↓"
    '&mmv MOVE_LEFT': "Mouse ←"
    '&mmv MOVE_RIGHT': "Mouse →"

    '&msc SCRL_UP': "Scroll ↑"
    '&msc SCRL_DOWN': "Scroll ↓"
    '&msc SCRL_LEFT': "Scroll ←"
    '&msc SCRL_RIGHT': "Scroll →"

    '&mkp LCLK': "$$mdi:mouse-left-click-outline$$"
    '&mkp RCLK': "$$mdi:mouse-right-click-outline$$"
    '&mkp MCLK': "Middle Click"
    '&mkp MB3': "Middle Click"
    '&mkp MB4': "Back Click"
    '&mkp MB5': "Forward Click"

    # ▼▼ ここに正規表現マッピングを移動（※ raw_binding_map の中） ▼▼
    # &lt_exit_AML NUM KEY → {t: "KEY", h: "NUM"}
    "/&lt_exit_AML\\s+([0-9]+)\\s+([^\\s]+)/":
      t: "\\2"
      h: "\\1"

    # &lt NUM KEY → {t: "KEY", h: "NUM"}
    "/&lt\\s+([0-9]+)\\s+([^\\s]+)/":
      t: "\\2"
      h: "\\1"

    # &mt_exit_AML_on_tap HOLD TAP → {t: "TAP", h: "HOLD"}
    "/&mt_exit_AML_on_tap\\s+([^\\s]+)\\s+([^\\s]+)/":
      t: "\\2"
      h: "\\1"

    # &mt_exit_AML HOLD TAP → {t: "TAP", h: "HOLD"}
    "/&mt_exit_AML\\s+([^\\s]+)\\s+([^\\s]+)/":
      t: "\\2"
      h: "\\1"
    # ▲▲ 正規表現マッピングここまで ▲▲

  zmk_combos:
    combo_btclr:  {align: bottom}
    combo_undo:   {align: bottom}
    combo_mouse:  {align: bottom}
    combo_semi:   {align: bottom}
    combo_winq:   {align: top, w: 36}
    combo_capswd: {draw_separate: true}
    combo_lpar:   {draw_separate: true}
    combo_rpar:   {draw_separate: true}
    combo_esc:    {draw_separate: true}
    combo_ret:    {draw_separate: true}
    combo_lock:   {draw_separate: true}
    combo_indbat: {align: top, o: 0.25}
    combo_indcon: {align: top}
    # ※ ここはオプション辞書のみ。アイコン等の直接指定は不可のため削除しました

  zmk_keycode_map:
    LC(BSPC): "$$mdi:backspace$$"
    LC(DEL): "$$mdi:backspace-reverse$$"
    LS(TAB): "$$mdi:keyboard-tab-reverse$$"
    
    LC(TAB): "$$mdi:arrow-right-bold-box$$"
    LC(LS(TAB)): "$$mdi:arrow-left-bold-box$$"

    LC(LG(LEFT)): "$$mdi:arrow-left-bold-box-outline$$"
    LC(LG(RIGHT)): "$$mdi:arrow-right-bold-box-outline$$"
    
    LC(LS(LALT)): "$$mdi:star-three-points-outline$$"
    LC(LS(LA(LGUI))): "$$mdi:star-four-points-outline$$"
    LC(HOME): "$$mdi:format-vertical-align-top$$"
    LC(END): "$$mdi:format-vertical-align-bottom$$"

    LC(INS): "$$mdi:content-copy$$"
    LC(C): "$$mdi:content-copy$$"
    LS(INS): "$$mdi:content-paste$$"
    LC(V): "$$mdi:content-paste$$"
    LS(DEL): "$$mdi:content-cut$$"
    LC(X): "$$mdi:content-cut$$"
    LC(DE_Z): "$$mdi:undo$$"
    LC(DE_Y): "$$mdi:redo$$"
    LC(LS(DE_Z)): "$$mdi:redo$$"

    LC(A): "$$mdi:select-all$$"
    LC(F): "$$mdi:text-search$$"
    LC(W): "$$mdi:close-box-outline$$"
    LA(F4): "$$mdi:close-box-outline$$"

    LC(DE_PLUS): "$$mdi:magnify-plus-outline$$"
    LC(DE_MINUS): "$$mdi:magnify-minus-outline$$"
    LC(N0): "$$mdi:magnify-remove-outline$$"

    LG(L): "$$mdi:lock-outline$$"
    
    LALT: "ALT"
    LEFTALT: "ALT"
    LEFT_ALT: "ALT"

    SPACE: "$$mdi:keyboard-space$$"
    ESC: "$$mdi:keyboard-esc$$"

    RETURN: "$$mdi:keyboard-return$$"
    RET: "$$mdi:keyboard-return$$"
    
    BACKSPACE: "$$mdi:backspace-outline$$"
    BSPC: "$$mdi:backspace-outline$$"
    
    DELETE: "$$mdi:backspace-reverse-outline$$"
    DEL: "$$mdi:backspace-reverse-outline$$"
    
    LCTRL: "$$mdi:apple-keyboard-control$$"
    LEFT_CONTROL: "$$mdi:apple-keyboard-control$$"
    
    RCTRL: "$$mdi:apple-keyboard-control$$"
    RIGHT_CONTROL: "$$mdi:apple-keyboard-control$$"
    
    LSHFT: "$$mdi:apple-keyboard-shift$$"
    LSHIFT: "$$mdi:apple-keyboard-shift$$"
    LEFT_SHIFT: "$$mdi:apple-keyboard-shift$$"
    
    RSHFT: "$$mdi:apple-keyboard-shift$$"
    RSHIFT: "$$mdi:apple-keyboard-shift$$"
    RIGHT_SHIFT: "$$mdi:apple-keyboard-shift$$"

    LGUI: "$$mdi:microsoft-windows$$"
    RGUI: "$$mdi:microsoft-windows$$"
    LWIN: "$$mdi:microsoft-windows$$"
    LEFT_WIN: "$$mdi:microsoft-windows$$"


    TAB: "$$mdi:keyboard-tab$$"

    CLCK: "$$mdi:apple-keyboard-caps$$"
    CAPS: "$$mdi:apple-keyboard-caps$$"
    CAPSLOCK: "$$mdi:apple-keyboard-caps$$"

    SCROLLLOCK: "$$mdi:arrow-vertical-lock$$"
    SLCK: "$$mdi:arrow-vertical-lock$$"
    SCLK: "$$mdi:arrow-vertical-lock$$"

    KP_NLCK: "$$mdi:numeric-off$$"

    PSCRN: "$$mdi:monitor-screenshot$$"
    PAUSE_BREAK: "Pause Break"
    
    C_PREV: "⏮"
    C_NEXT: "⏭"
    C_PLAY_PAUSE: "⏯"
    C_MUTE: "🔇"
    C_VOLUME_UP: "🔊"
    C_VOLUME_DOWN: "🔉"
    C_PP: "$$mdi:play-pause$$"
 
    C_BRI_UP: "$$phosphor:bold/sun$$"
    C_BRI_DN: "$$phosphor:bold/sun-dim$$"
    
    C_POWER: "$$mdi:power$$"
    C_SLEEP: "$$mdi:power-sleep$$"
    C_AL_CALC: "$$mdi:calculator$$"
    
    UP: "$$mdi:arrow-up$$"
    DOWN: "$$mdi:arrow-down$$"
    LEFT: "$$mdi:arrow-left$$"
    RIGHT: "$$mdi:arrow-right$$"
    
    PG_UP: "Page Up"
    PG_DN: "Page Down"

    SECT: "§"
    DEG: "°"
    EURO: "€"

    A_UMLAUT: "Ä"
    AE: "Ä"
    U_UMLAUT: "Ü"
    UE: "Ü"
    O_UMLAUT: "Ö"
    OE: "Ö"
    SZ: "ß"
    ACUTE: "´"
    
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: "$"
    DLLR: "$"
    PERCENT: "%"
    PRCNT: "%"
    CARET: "^"
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: "("
    LPAR: "("
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    EQUAL: "="
    PLUS: "+"
    MINUS: "-"
    UNDERSCORE: "_"
    UNDER: "_"
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: "\\"
    BSLH: "\\"
    PIPE: "|"
    NON_US_BACKSLASH: "\\"
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ";"
    SEMI: ";"
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: "\""
    DQT: "\""
    COMMA: ","
    LESS_THAN: "<"
    LT: "<"
    PERIOD: "."
    DOT: "."
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    INTERNATIONAL_5 : "mu-henkan"
    INTERNATIONAL_4 : "henkan"


    LS(NUMBER_1) : "!"
    LS(NUMBER_2) : """
    LS(NUMBER_3) : "#"
    LS(NUMBER_4) : "$" 
    LS(N5)       : "%" 
    LS(NUMBER_6) : "&"
    LS(NUMBER_7) : "'"
    LS(NUMBER_8) : "("
    LS(NUMBER_9) : ")"
    LS(N0): ""
    LS(MINUS) : "~"
    LS(EQUAL) : "|"
    LS(INT3): "|"
    LS(INTERNATIONAL_1): "_"