########################################
# 基本機能
########################################
CONFIG_NFCT_PINS_AS_GPIOS=y         # NFCピンをGPIOとして使用可能にする

########################################
# ロータリーエンコーダ設定
########################################
CONFIG_EC11=y                       # EC11ロータリーエンコーダを有効化
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y # EC11のイベント処理をグローバルスレッドで実行

########################################
# バッテリー管理
########################################
CONFIG_ZMK_BATTERY_REPORTING=y      # バッテリーレベルをホスト側へレポート
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y    # セントラル側でペリフェラルのバッテリーレベルを代理転送
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y # セントラル側がペリフェラルのバッテリーレベルを取得
