########################################
# Basic Features
########################################
CONFIG_NFCT_PINS_AS_GPIOS=y         # Enable using NFC pins as GPIO

########################################
# Rotary Encoder Settings
########################################
CONFIG_EC11=y                       # Enable EC11 rotary encoder
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y # Handle EC11 events in a global thread

########################################
# Battery Management
########################################
CONFIG_ZMK_BATTERY_REPORTING=y       # Report battery level to host
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y    # Central proxies battery level of peripherals
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y # Central fetches battery level from peripherals
