name: Build
on:
  workflow_dispatch:
  pull_request:
  # push:
  #   paths:
  #     - config/**
  #     - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@abb64ba316c29caddc49727ca2cac2f0ed5970c7 # v0.3.0